dist: trusty
os: linux

language: node_js
node_js:
  - "10.14.2"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - npm install
  - xvfb-run -a npm run ci

after_script:
  - cat ./coverage/resume/lcov.info | ./node_modules/coveralls/bin/coveralls.js
